# Phase4 Configuration

debug: false

input:
  device: -1
  channels: 1
  sample_rate: 44100
  buffer_size: 256
  low_latency: true

dsp:
  enabled: true
  fft_window: "Hamming"

transport:
  udp_enabled: false
  udp_send_address: "127.0.0.1:8888"
  udp_send_interval: "33.33ms"
